apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-1
  namespace: default
  labels:
    app: pv-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv
  name: use-pvspec-matanmeshi
spec:
  containers:
    - image: nginx
      name: use-pv
      volumeMounts:
        - mountPath: /data
          name: pv-1
  volumes:
    - name: pv-1
      persistentVolumeClaim:
        claimName: pv-1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
