apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
    - image: nginx
      name: alpha
      imagePullPolicy: IfNotPresent
      env:
        - name: alpha
    - image: busybox
      name: beta
      imagePullPolicy: IfNotPresent
      env:
        - name: beta
      command: ["sleep", "4800"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
