apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-web-app
  namespace: default
  labels:
    app: hr-web-app
spec:
  selector:
    matchLabels:
      app: hr-web-app
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hr-web-app
    spec:
      containers:
        - name: hr-web-app
          image: kodekloud/webapp-color
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
              name: hr-web-app
      restartPolicy: Always
